version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Bawa@2004
      MYSQL_DATABASE: cr_db
      MYSQL_USER: root
      MYSQL_PASSWORD: Bawa@2004
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  spring-boot-app:
    build: .
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/courseIITBOMBAY
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Bawa@2004
    depends_on:
      - db

volumes:
  db_data:
